server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurantes_plazoleta
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
appDescription: "Restaurantes Plazoleta"
appVersion: "1.0.0"
