server:
  port: 8082

application:
  security:
    jwt:
      secret-key: 19b02086edcba74510ff59eaa84183b78ffdd8c8f3888de4aa831f9acddcbec9

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurantes_plazoleta
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Restaurantes Plazoleta"
appVersion: "1.0.0"

categorias.map:
  appetizer: "entrada"
  breakfast: "desayuno"
  salad: "ensalada"